### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MexicanRaindeer** [wyozi/cyan#3]
I don't know why this happens... Scala is not a language I know.

`java.lang.RuntimeException: Duplicate mappings:
        /root/activator-dist-1.3.7/target/universal/stage/lib/org.scala-lang.scala-library-2.11.7.jar
from
        /root/activator-dist-1.3.7/lib/org.scala-lang.scala-library-2.11.7.jar
                /root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar
        at scala.sys.package$.error(package.scala:27)
        at sbt.Sync$.noDuplicateTargets(Sync.scala:67)
        at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:26)
        at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:23)
        at com.typesafe.sbt.packager.Stager$.stageFiles(Stager.scala:26)
        at com.typesafe.sbt.packager.Stager$.stage(Stager.scala:40)
        at com.typesafe.sbt.packager.universal.UniversalPlugin$$anonfun$makePackageSettingsForConfig$7.apply(UniversalPlugin.scala:86)
        at com.typesafe.sbt.packager.universal.UniversalPlugin$$anonfun$makePackageSettingsForConfig$7.apply(UniversalPlugin.scala:86)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (cyan/*:stage) Duplicate mappings:
[error]         /root/activator-dist-1.3.7/target/universal/stage/lib/org.scala-lang.scala-library-2.11.7.jar
[error] from
[error]         /root/activator-dist-1.3.7/lib/org.scala-lang.scala-library-2.11.7.jar
[error]                 /root/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar
[error] Total time: 39 s, completed Mar 22, 2016 9:16:05 PM
`

**Comment by wyozi** [comment]
Yep, scala likes being very unfriendly with error messages at times.

As to what causes your error; no idea, but it's probably not Cyan. I'd first advise to try removing all `org.scala-lang.scala-library-2.11.7.jar` files except one (which might work because it mentions duplicate).

**Comment by MexicanRaindeer** [comment]
Fixed it, thanks!
